Repository itx-academy-2/spa-orders, pull requests merged in 2025-03, with the labels that each got.

#15 Sale products filtering and sorting
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.test.tsx
  code/src/hooks/use-filters-with-apply/parse-serialized-set/parseSerializedSet.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.ts
  code/src/pages/sales/SalesPage.constants.test.tsx
  code/src/pages/sales/SalesPage.constants.tsx
  code/src/pages/sales/SalesPage.scss
  code/src/pages/sales/SalesPage.test.tsx
  code/src/pages/sales/SalesPage.tsx
  code/src/pages/sales/SalesPage.types.ts
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.styles.scss
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.test.tsx
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.tsx
  code/src/pages/sales/hooks/useSalesFilter.ts
  code/src/pages/sales/hooks/useSalesFilters.test.ts
  code/src/pages/sales/messages/en.json
  code/src/pages/sales/messages/uk.json
  code/src/store/api/productsApi.ts
  code/src/types/product.types.ts
Labels: feature, user story, sprint 3

#16 hotfix
  code/src/pages/sales/SalesPage.test.tsx
  code/src/pages/sales/SalesPage.tsx
Labels: sprint 3, hotfix

#21 [GS2-116] Fixed filter resetting in filters drawer
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.test.tsx
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.tsx
Labels: bug, sprint 4

#22 [GS2-115] Fixed arrows for sale filters
  code/src/containers/dashboard-orders-filter-drawer/components/filter-record-accordion/FilterRecordAccordion.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/components/filter-record-accordion/FilterRecordAccordion.tsx
Labels: bug, sprint 4

#23 [GS2-119] Implemented custom confirmation modal. Added it to product discount removal.
  code/src/containers/confirm-dialog/ConfirmDialog.styles.scss
  code/src/containers/confirm-dialog/ConfirmDialog.test.tsx
  code/src/containers/confirm-dialog/ConfirmDialog.tsx
  code/src/containers/confirm-dialog/ConfirmDialog.types.ts
  code/src/containers/confirm-dialog/messages/en.json
  code/src/containers/confirm-dialog/messages/index.ts
  code/src/containers/confirm-dialog/messages/uk.json
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.test.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.tsx
  code/src/containers/forms/product-form/hooks/use-update-product/useUpdateProduct.ts
  code/src/containers/forms/product-form/messages/en.json
  code/src/containers/forms/product-form/messages/uk.json
  code/src/context/confirm/ConfirmContext.test.tsx
  code/src/context/confirm/ConfirmContext.tsx
  code/src/context/confirm/ConfirmContext.types.ts
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/messages.ts
  code/src/pages/sales/SalesPage.constants.tsx
  code/src/pages/sales/SalesPage.tsx
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.test.tsx
  code/src/pages/sales/components/sales-filter-drawer/SalesFilterDrawer.tsx
  code/src/pages/sales/hooks/useSalesFilter.ts
  code/src/pages/sales/hooks/useSalesFilters.test.ts
Labels: feature, sprint 4

#24 [GS2-121] New behaviour for max discount value and handle negative final price
  code/src/containers/forms/product-form/components/create-additional-info/CreateAdditionalInfo.test.tsx
  code/src/containers/forms/product-form/components/create-additional-info/CreateAdditionalInfo.tsx
Labels: bug, feature, sprint 4

#20 [GS2-64] Help center page
  code/package-lock.json
  code/package.json
  code/src/components/app-search-input/AppSearchInput.tsx
  code/src/constants/api-tags.ts
  code/src/constants/requests.ts
  code/src/constants/routes.ts
  code/src/hooks/use-article-details/useArticleDetails.test.tsx
  code/src/hooks/use-article-details/useArticleDetails.ts
  code/src/layouts/footer/components/footer-banner/FooterBanner.tsx
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/help-center/HelpCenterPage.scss
  code/src/pages/help-center/HelpCenterPage.test.tsx
  code/src/pages/help-center/HelpCenterPage.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/HelpCenterAccordionItem.test.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/HelpCenterAccordionItem.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.styles.scss
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.test.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.types.ts
  code/src/pages/help-center/messages/en.json
  code/src/pages/help-center/messages/index.ts
  code/src/pages/help-center/messages/uk.json
  code/src/routes/guestRoutes.tsx
  code/src/store/api/articlesApi.ts
  code/src/types/article.types.ts
Labels: feature, user story, sprint 4

#28 [GS2-136, GS2-139] Fixed cart drawer bug, fixed help center articles bug
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/hooks/use-add-to-cart-or-open-drawer/useAddToCartOrOpenDrawer.tsx
  code/src/hooks/use-article-details/useArticleDetails.test.tsx
  code/src/hooks/use-article-details/useArticleDetails.ts
  code/src/pages/help-center/HelpCenterPage.tsx
  code/src/pages/home/HomePage.tsx
  code/src/store/api/articlesApi.ts
  code/src/types/article.types.ts
  code/src/types/cart.types.ts
Labels: bug

#29 [GS2-138] Improve help center view
  code/src/layouts/footer/Footer.tsx
Labels: sprint 4

#33 Release 2.2.1 - hotfix
  code/package-lock.json
  code/package.json
  code/src/constants/cart.ts
  code/src/containers/cart-drawer/CartDrawer.test.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/hooks/use-user-cart-items/useUserCartItems.test.ts
  code/src/hooks/use-user-cart-items/useUserCartItems.ts
  code/src/pages/cart/CartPage.tsx
  code/src/store/slices/localCart.ts
  code/src/types/cart.types.ts
  code/src/utils/set-local-storage-cart/setLocalStorageCart.test.ts
Labels: release, hotfix, sprint 5

#35 Filter metrics for manager and admin
  code/package-lock.json
  code/package.json
  code/src/constants/requests.ts
  code/src/constants/routes.ts
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/layouts/dashboard-layout/DashboardLayout.constants.tsx
  code/src/layouts/dashboard-layout/components/dashboard-admin-tab-layout/DashboardAdminLayout.constants.tsx
  code/src/layouts/dashboard-layout/components/dashboard-manager-tab-layout/DashboardManagerLayout.constants.tsx
  code/src/layouts/dashboard-layout/messages/en.json
  code/src/layouts/dashboard-layout/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-metrics/DashboardMetricsPage.constants.ts
  code/src/pages/dashboard/dashboard-metrics/DashboardMetricsPage.scss
  code/src/pages/dashboard/dashboard-metrics/DashboardMetricsPage.test.tsx
  code/src/pages/dashboard/dashboard-metrics/DashboardMetricsPage.tsx
  code/src/pages/dashboard/dashboard-metrics/components/dashboard-metrics-chart/DashboardMetricsChart.test.tsx
  code/src/pages/dashboard/dashboard-metrics/components/dashboard-metrics-chart/DashboardMetricsChart.tsx
  code/src/pages/dashboard/dashboard-metrics/components/dashboard-metrics-skeleton/DashboardMetricsSkeleton.scss
  code/src/pages/dashboard/dashboard-metrics/components/dashboard-metrics-skeleton/DashboardMetricsSkeleton.test.tsx
  code/src/pages/dashboard/dashboard-metrics/components/dashboard-metrics-skeleton/DashboardMetricsSkeleton.tsx
  code/src/pages/dashboard/dashboard-metrics/messages/en.json
  code/src/pages/dashboard/dashboard-metrics/messages/index.ts
  code/src/pages/dashboard/dashboard-metrics/messages/uk.json
  code/src/pages/dashboard/dashboard-metrics/utils/get-chart-labels/get-chart-label.test.ts
  code/src/pages/dashboard/dashboard-metrics/utils/get-chart-labels/get-chart-labels.ts
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/metricsApi.ts
  code/src/types/metric.types.ts
Labels: feature, user story, sprint 5

#36 [GS2-67] Improve shop manager orders column view
  code/src/containers/tables/orders-table/OrdersTable.constants.ts
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/containers/tables/orders-table/messages/en.json
  code/src/containers/tables/orders-table/messages/uk.json
Labels: feature, user story, sprint 5

#37 [GS2-140] Added option to sort by bestsellers
  code/src/containers/best-sellers/BestSellers.test.tsx
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.constants.tsx
  code/src/pages/products/messages/en.json
  code/src/pages/products/messages/uk.json
Labels: feature, user story, sprint 5
