Repository itx-academy-2/spa-orders, pull requests merged in 2025-04, with the labels that each got.

#38 [GS2-67] Fix total price column view with dash
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
Labels: hotfix, sprint 5

#40 [GS2-159] Fixed sorting dropdown bug
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/sales/SalesPage.tsx
Labels: bug, hotfix

#41 Release 2.3.1 - hotfix
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/sales/SalesPage.tsx
Labels: release

#42 [GS2-92] Implement search for articles
  code/src/components/help-center-search-dropdown/help-center-search-dropdown-container/HelpCenterSearchDropdownContainer.test.tsx
  code/src/components/help-center-search-dropdown/help-center-search-dropdown-container/HelpCenterSearchDropdownContainer.tsx
  code/src/components/help-center-search-dropdown/help-center-search-input-dropdown/HelpCenterSearchInputDropdown.test.tsx
  code/src/components/help-center-search-dropdown/help-center-search-input-dropdown/HelpCenterSearchInputDropdown.tsx
  code/src/components/help-center-search-input/HelpCenterSearchInput.test.tsx
  code/src/components/help-center-search-input/HelpCenterSearchInput.tsx
  code/src/constants/requests.ts
  code/src/hooks/use-article-details/useArticleDetails.ts
  code/src/pages/help-center/HelpCenterPage.scss
  code/src/pages/help-center/HelpCenterPage.test.tsx
  code/src/pages/help-center/HelpCenterPage.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/HelpCenterAccordionItem.test.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/HelpCenterAccordionItem.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/components/HelpCenterAccordionItemSkeleton.test.tsx
  code/src/pages/help-center/components/help-cener-accordion-item/components/HelpCenterAccordionItemSkeleton.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.test.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.tsx
  code/src/pages/help-center/components/help-center-accordion/HelpCenterAccordion.types.ts
  code/src/pages/help-center/components/help-center-skeleton/HelpCenterSkeleton.test.tsx
  code/src/pages/help-center/components/help-center-skeleton/HelpCenterSkeleton.tsx
  code/src/pages/help-center/messages/en.json
  code/src/pages/help-center/messages/uk.json
  code/src/store/api/articlesApi.ts
Labels: feature, user story, Sprint 6

#43 [GS2-111] Suggestion to buy smth
  code/src/constants/api-tags.ts
  code/src/constants/common.ts
  code/src/constants/requests.ts
  code/src/hooks/use-track-visits/useTrackVisits.ts
  code/src/pages/help-center/HelpCenterPage.scss
  code/src/pages/help-center/HelpCenterPage.test.tsx
  code/src/pages/help-center/HelpCenterPage.tsx
  code/src/pages/help-center/hooks/use-suggested-product/useSuggestedProduct.ts
  code/src/pages/help-center/messages/en.json
  code/src/pages/help-center/messages/uk.json
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/store/api/productsApi.ts
  code/src/types/common.ts
  code/src/types/product.types.ts
  code/src/utils/get-previous-visits-data/get-previous-visits-data.ts
  code/src/utils/is-valid-category/isValidCategory.ts
Labels: user story, Sprint 6

#44 [GS2-176] Added message displaying when concurrency error occurs
  code/src/containers/forms/product-form/hooks/use-update-product/useUpdateProduct.ts
  code/src/containers/forms/product-form/messages/en.json
  code/src/containers/forms/product-form/messages/uk.json
Labels: enhancement, Sprint 6
