Repository itx-academy-2/spa-orders, pull requests merged in 2025-07, with the labels that each got.

#50 [GS3-10] Fix long name in manager dashboard
  code/src/containers/tables/products-table/ProductsTable.constants.ts
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.test.tsx
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.tsx
  code/src/types/product.types.ts
  code/src/utils/truncate-with-ellipsis/truncateWithEllipsis.test.ts
  code/src/utils/truncate-with-ellipsis/truncateWithEllipsis.ts
Labels: bug

#63 [GS-43] Implement `Personal Information` section
  code/src/components/profile-personal-information/PersonalInformation.module.scss
  code/src/components/profile-personal-information/PersonalInformation.test.tsx
  code/src/components/profile-personal-information/PersonalInformation.tsx
  code/src/components/profile-personal-information/messages/en.json
  code/src/components/profile-personal-information/messages/index.ts
  code/src/components/profile-personal-information/messages/uk.json
  code/src/containers/user-account/profile/Profile.module.scss
  code/src/containers/user-account/profile/Profile.test.tsx
  code/src/containers/user-account/profile/Profile.tsx
  code/src/messages.ts
  code/src/routes/protectedRoutes.tsx
Labels: feature

#59 [GS3-38] Implemented Favorite button and `My Wishlist` page
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/constants/api-tags.ts
  code/src/constants/requests.ts
  code/src/containers/user-account/my-wishlist/MyWishlist.module.scss
  code/src/containers/user-account/my-wishlist/MyWishlist.test.tsx
  code/src/containers/user-account/my-wishlist/MyWishlist.tsx
  code/src/containers/user-account/my-wishlist/messages/en.json
  code/src/containers/user-account/my-wishlist/messages/index.ts
  code/src/containers/user-account/my-wishlist/messages/uk.json
  code/src/hooks/use-toggle-favorite/useToggleFavorite.test.ts
  code/src/hooks/use-toggle-favorite/useToggleFavorite.ts
  code/src/messages.ts
  code/src/pages/user-account/Wishlist/WishlistPage.tsx
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/wishlistApi.ts
Labels: feature

#66 [GS3-59] Implemented backend logic for My Wishlist
  mock-backend/src/app.js
  mock-backend/src/controllers/wishlistController.js
  mock-backend/src/middlewares/authMiddleware.js
  mock-backend/src/routes/wishlistRoutes.js
Labels: feature

#68 [GS3-63] Added missing Like (Heart) Icon for Product on Sale
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-sale-card/SaleProductCard.test.tsx
  code/src/components/product-sale-card/SaleProductCard.tsx
  code/src/containers/user-account/my-wishlist/MyWishlist.module.scss
  code/src/containers/user-account/my-wishlist/MyWishlist.tsx
Labels: bug, invalid

#73 [GS3-45] Added email and password section to the profile
  code/src/components/profile-email-password/EmailAndPassword.module.scss
  code/src/components/profile-email-password/EmailAndPassword.test.tsx
  code/src/components/profile-email-password/EmailAndPassword.tsx
  code/src/components/profile-email-password/messages/en.json
  code/src/components/profile-email-password/messages/index.ts
  code/src/components/profile-email-password/messages/uk.json
  code/src/components/profile-personal-information/PersonalInformation.module.scss
  code/src/components/profile-personal-information/PersonalInformation.test.tsx
  code/src/components/profile-personal-information/PersonalInformation.tsx
  code/src/components/profile-personal-information/PersonalInformation.types.ts
  code/src/containers/user-account/profile/Profile.module.scss
  code/src/containers/user-account/profile/Profile.test.tsx
  code/src/containers/user-account/profile/Profile.tsx
  code/src/containers/user-account/profile/messages/en.json
  code/src/containers/user-account/profile/messages/uk.json
  code/src/messages.ts
Labels: feature

#81 [GS-68] Implemented pagination for My Wishlist, updated endpoints
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/ProductCard.types.ts
  code/src/components/product-sale-card/SaleProductCard.tsx
  code/src/constants/requests.ts
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/containers/products-container/ProductsContainer.types.ts
  code/src/containers/user-account/my-wishlist/MyWishlist.test.tsx
  code/src/containers/user-account/my-wishlist/MyWishlist.tsx
  code/src/containers/user-account/view-history/UserViewHistory.test.tsx
  code/src/containers/user-account/view-history/UserViewHistory.tsx
  code/src/hooks/use-toggle-favorite/useToggleFavorite.test.ts
  code/src/hooks/use-toggle-favorite/useToggleFavorite.ts
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/sales/SalesPage.test.tsx
  code/src/pages/sales/SalesPage.tsx
  code/src/store/api/wishlistApi.ts
Labels: feature
