Repository itx-academy-2/spa-orders, pull requests merged in 2025-08, with the labels that each got.

#72 [GS3-64] Added Like (Favorite) button to Product Details
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-sale-card/SaleProductCard.tsx
  code/src/pages/product-details/ProductDetailsPage.test.tsx
  code/src/pages/product-details/ProductDetailsPage.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.scss
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.test.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
Labels: bug

#98 [GS3-98] Added addresses endpoint and improved tests
  code/src/containers/forms/delivery-form/DeliveryForm.test.tsx
  code/src/containers/forms/delivery-form/DeliveryForm.tsx
  code/src/pages/cart/CartPage.test.tsx
  code/src/store/api/addressApi.ts
  code/src/store/api/ordersApi.ts
  code/src/types/address.types.ts
Labels: feature

#93 [GS3-91] Improved visibility of sidebar menu
  code/src/components/sidebar/Sidebar.module.scss
  code/src/components/sidebar/sidebar-menu/SidebarMenu.module.scss
  code/src/layouts/account-layout/AccountLayout.module.scss
Labels: enhancement

#97 [GS-6] Fixed price with discount in cart drawer
  code/src/components/quantity-selector/QuantitySelector.module.scss
  code/src/components/quantity-selector/QuantitySelector.test.tsx
  code/src/components/quantity-selector/QuantitySelector.tsx
  code/src/components/quantity-selector/QuantitySelector.types.ts
  code/src/containers/cart-drawer/CartDrawer.scss
  code/src/containers/cart-drawer/CartDrawer.test.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.scss
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.test.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.tsx
  code/src/pages/cart/components/cart-item/CartItem.scss
  code/src/pages/cart/components/cart-item/CartItem.test.tsx
  code/src/pages/cart/components/cart-item/CartItem.tsx
  code/src/types/cart.types.ts
Labels: bug

#105 [GS-102] Hided `Change password` button
  code/src/components/profile-email-password/EmailAndPassword.module.scss
Labels: bug
